services:
  postgres:
    image: postgres:17
    container_name: todo_postgres
    environment:
      POSTGRES_DB: techzen_academy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
